-- Do Not Edit This File.
-- [32] = default; [33] = line number; [34] = brace highlight; [35] = unmatched brace
return {
	common = {
		style = {
			caret = {
				back = "#8afff0"
			},
			comment = {
				fore = "#007f75",
				italic = true
			},
			docComment = {
				fore = "#993300",
				italic = true
			},
			docKeyword = {
				bold = true,
				fore = "#663300",
				italic = true
			},
			doubleQuotedString = {
				fore = "#00ccbb"
			},
			error = {
				back = "#ff0000",
				eolfilled = true,
				fore = "#ffff00"
			},
			find = {
				back = "#ff19e3"
			},
			foldMargin = {
				back = "#007f75"
			},
			identifier = {

			},
			inactive = {
				back = "#ffaa99",
				eolfilled = true
			},
			keyword = {
				bold = true,
				fore = "#267f78"
			},
			label = {
				fore = "#800000"
			},
			number = {
				fore = "#00ccbb"
			},
			operator = {
				bold = true
			},
			preprocessor = {
				bold = true,
				fore = "#00ffea"
			},
			ref = {
				back = "#cc4000"
			},
			selection = {
				back = "#00d6c1"
			},
			singleQuotedString = {
				fore = "#00ccbb"
			},
			unclosedDoubleQuotedString = {
				back = "#ffaa99",
				eolfilled = true
			},
			unclosedSingleQuotedString = {
				back = "#ffaa99",
				eolfilled = true
			},
			whitespace = {
				fore = "#808080"
			}
		}
	},
	style = {
		[32] = {
			back = "#ffffff",
			fore = "#000000"
		},
		[33] = {
			back = "#00ffea"
		},
		[34] = {
			back = "#09cc4a",
			bold = true
		},
		[35] = {
			back = "#cc1b14",
			bold = true
		}
	},
	udb = {
		style = {
			ada = {
				globalVariableNames = {
					bold = true,
					fore = "#5555ff",
					underline = true
				},
				localVariableNames = {
					fore = "#5555ff",
					italic = true
				},
				packageNames = {
					fore = "#005500"
				}
			},
			cs = {
				classNames = {
					fore = "#005500"
				},
				methodNames = {
					fore = "#00aa00"
				}
			},
			cxx = {
				classNames = {
					fore = "#005500"
				},
				functionNames = {
					fore = "#00aa00"
				},
				globalVariableNames = {
					bold = true,
					fore = "#5555ff",
					underline = true
				},
				localVariableNames = {
					fore = "#5555ff",
					italic = true
				}
			},
			fortran = {
				subprogramNames = {
					fore = "#00aa00"
				}
			},
			java = {
				classNames = {
					fore = "#005500"
				},
				methodNames = {
					fore = "#00aa00"
				}
			},
			jovial = {
				subroutineNames = {
					fore = "#00aa00"
				}
			},
			pascal = {
				routineNames = {
					fore = "#00aa00"
				}
			},
			python = {
				classNames = {
					fore = "#005500"
				}
			},
			vhdl = {
				subprogramNames = {
					fore = "#00aa00"
				}
			}
		}
	}
}
