-- Do Not Edit This File.
-- [32] = default; [33] = line number; [34] = brace highlight; [35] = unmatched brace
return {
	common = {
		style = {
			caret = {
				back = "#1d1d1d"
			},
			comment = {
				fore = "#00bf00",
				italic = true
			},
			docComment = {
				fore = "#993300",
				italic = true
			},
			docKeyword = {
				bold = true,
				fore = "#663300",
				italic = true
			},
			doubleQuotedString = {
				fore = "#dbc900"
			},
			error = {
				back = "#ff0000",
				eolfilled = true,
				fore = "#ffff00"
			},
			find = {
				back = "#ffff7f"
			},
			foldMargin = {
				back = "#262626"
			},
			identifier = {

			},
			inactive = {
				back = "#1f0000",
				eolfilled = true
			},
			keyword = {
				bold = true,
				fore = "#ff0000"
			},
			label = {
				fore = "#800000"
			},
			number = {
				fore = "#00d0d0"
			},
			operator = {
				bold = true
			},
			preprocessor = {
				bold = true,
				fore = "#008000"
			},
			ref = {
				back = "#55ffff"
			},
			selection = {
				back = "#4d4d4d"
			},
			singleQuotedString = {
				fore = "#dbc900"
			},
			unclosedDoubleQuotedString = {
				back = "#1f0000",
				eolfilled = true
			},
			unclosedSingleQuotedString = {
				back = "#1f0000",
				eolfilled = true
			},
			whitespace = {
				fore = "#808080"
			}
		}
	},
	style = {
		[32] = {
			back = "#000000",
			fore = "#ffffff"
		},
		[33] = {
			back = "#a0a0a0"
		},
		[34] = {
			back = "#009000",
			bold = true
		},
		[35] = {
			back = "#bc0000",
			bold = true
		}
	},
	udb = {
		style = {
			ada = {
				globalVariableNames = {
					bold = true,
					fore = "#ff557f",
					underline = true
				},
				localVariableNames = {
					fore = "#ff557f",
					italic = true
				},
				packageNames = {
					fore = "#ff5500"
				},
				subprogramNames = {
					fore = "#ff007f"
				}
			},
			cs = {
				classNames = {
					fore = "#ff5500"
				},
				methodNames = {
					fore = "#ff007f"
				}
			},
			cxx = {
				classNames = {
					fore = "#ff5500"
				},
				functionNames = {
					fore = "#ff007f"
				},
				globalVariableNames = {
					bold = true,
					fore = "#ff557f",
					underline = true
				},
				localVariableNames = {
					fore = "#ff557f",
					italic = true
				}
			},
			fortran = {
				subprogramNames = {
					fore = "#ff007f"
				}
			},
			java = {
				classNames = {
					fore = "#ff5500"
				},
				methodNames = {
					fore = "#ff007f"
				}
			},
			jovial = {
				subroutineNames = {
					fore = "#ff007f"
				}
			},
			pascal = {
				routineNames = {
					fore = "#ff007f"
				}
			},
			python = {
				classNames = {
					fore = "#ff5500"
				},
				functionNames = {
					fore = "#ff007f"
				}
			},
			vhdl = {
				subprogramNames = {
					fore = "#ff007f"
				}
			}
		}
	}
}
